name = "gods-eye-view-proxy"
main = "index.js"
compatibility_date = "2024-01-01"
workers_dev = true

[vars]
# Add your API keys here if you have them
# OPENSKY_CLIENT_ID = ""
# OPENSKY_CLIENT_SECRET = ""
